version: '3.8'

services:
  postgres_db:
    image: postgres:16
    container_name: maritima_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
    ports:
      - "5433:5432"
    volumes:
      - ./postgres-init:/docker-entrypoint-initdb.d
    restart: unless-stopped

  redis_cache:
    image: redis:7
    container_name: maritima_redis
    ports:
      - "6379:6379"
    restart: unless-stopped
frontend:
    build: 
      context: ./frontend-maritimo
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      # Sincroniza tu código local con el contenedor para ver los cambios en tiempo real
      - ./frontend-maritimo:/app
      - /app/node_modules
    environment:
      # Ayuda a que los cambios al guardar se detecten rápido, especialmente en Windows
      - CHOKIDAR_USEPOLLING=true