spring.application.name=aduana
server.port=8082

# Conexión a PostgreSQL 
spring.datasource.url=jdbc:postgresql://localhost:5433/aduana_db
spring.datasource.username=admin
spring.datasource.password=adminpassword
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true