FROM node:20-alpine
WORKDIR /app

# Copiar dependencias primero para aprovechar el caché de Docker
COPY package*.json ./
RUN npm install

# Copiar el resto del código
COPY . .

# Exponer el puerto de Vite
EXPOSE 3000

# Iniciar servidor de desarrollo
CMD ["npm", "run", "dev"]