spring.application.name=logistica
server.port=8080

# Conexión a PostgreSQL 
spring.datasource.url=jdbc:postgresql://localhost:5433/logistica_db
spring.datasource.username=admin
spring.datasource.password=adminpassword
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Conexión a Redis para subastas en vivo
spring.data.redis.host=localhost
spring.data.redis.port=6379